// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

// Generated by scripts/generate-thought-v2-release-constants.mjs from exact profile bytes.
library ThoughtReleaseConstants {
    string internal constant RELEASE_ID_DOMAIN_TEXT = "INSHELL_THOUGHT_PROTOCOL_RELEASE";
    bytes32 internal constant RELEASE_ID_DOMAIN = keccak256(bytes(RELEASE_ID_DOMAIN_TEXT));
    string internal constant RENDERER_ID = "inshell.thought.svg.v2.binary-weave-32";
    bytes32 internal constant RENDERER_ID_HASH = keccak256(bytes(RENDERER_ID));
    bytes32 internal constant RENDERER_PROFILE_KECCAK256 = 0x6c124e260dcbfe801614b89da24bb31d407303e7cd93cc3e6a6ac372c862de88;
    string internal constant WORK_PROFILE_ID = "inshell.thought.work.v2";
    bytes32 internal constant WORK_PROFILE_ID_HASH = keccak256(bytes(WORK_PROFILE_ID));
    bytes32 internal constant WORK_PROFILE_KECCAK256 = 0x8b590ab95432b0dd5002a4fb1419475751bdf0210a73338bf633533005d182bb;
}
